name: whatsapp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.27
  mason_logger: ^0.2.10
  path: ^1.9.0
  universal_io: ^2.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
