name: 'whatsapp'
description: 'A sample command-line application.'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.42'
  mason_logger: '^0.2.10'
  path: '^1.9.0'
  universal_io: '^2.2.2'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
