name: 'whatsapp_documentation'
description: 'A new Flutter project.'
publish_to: 'none'
version: '0.0.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.6'
  path: '^1.9.0'
  general_lib: '^0.0.43'
  general_lib_flutter: '^0.0.24'
  documentation: '^0.0.2'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^3.0.0'
flutter: 
  uses-material-design: true
  assets: 
    - 'assets/logo/logo.png'
dependency_overrides: 
  pointycastle: '3.8.0'
