name: 'whatsapp_flutter'
description: 'A Library Full Package Template'
version: '0.0.0'
homepage: 'https://github.com/azkadev/whatsapp'
repository: 'https://github.com/azkadev/whatsapp'
issue_tracker: 'https://github.com/azkadev/whatsapp/issues'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter: null
publish_to: 'none'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
