name: 'whatsapp_client'
description: 'A Whatsapp Client Library for interact with whatsapp api unnofficial.'
version: '1.0.30'
homepage: 'https://github.com/azkadev/whatsapp'
repository: 'https://github.com/azkadev/whatsapp'
issue_tracker: 'https://github.com/azkadev/whatsapp/issues'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
executables:
  whatsapp_client: 'whatsapp_client'
  wa_cli: 'whatsapp_client'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'whatsapp'
  - 'whatsapp-client'
  - 'whatsapp-bot'
  - 'whatsapp-api'
environment:
  sdk: '>=3.6.0 <4.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependencies:
  general_lib: '^0.0.53'
  packagex: '^0.0.68'
  http: '^1.2.2'
  mason_logger: '^0.3.1'
  io_universe: '^0.0.2'
  path: '^1.9.0'
  mime: '^2.0.0'
  server_universe: '^0.0.29'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
